// <auto-generated />
using SysMonitor.Logic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SysMonitor.Logic.Migrations
{
    [DbContext(typeof(SysMonitorDbContext))]
    [Migration("20210403160223_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("SysMonitor.Logic.MonitoringData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpuName")
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsName")
                        .HasColumnType("TEXT");

                    b.Property<double>("RamCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("RamUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MonitoringData");
                });
#pragma warning restore 612, 618
        }
    }
}
