// <auto-generated />
using ArandaSoftware.SysMonitor.Logic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArandaSoftware.SysMonitor.Logic.Migrations
{
    [DbContext(typeof(SysMonitorDbContext))]
    partial class SysMonitorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("ArandaSoftware.SysMonitor.Logic.MonitoringData", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CpuName")
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsage")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("DiskUsage")
                        .HasColumnType("REAL");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("OsName")
                        .HasColumnType("TEXT");

                    b.Property<double>("RamCapacity")
                        .HasColumnType("REAL");

                    b.Property<double>("RamUsage")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("MonitoringData");
                });
#pragma warning restore 612, 618
        }
    }
}
